# frozen_string_literal: true

require "fileutils"
require "pathname"

module RailsDependencyPruner
  module Apply
    class BootPlanPatch
      attr_reader :app_root, :boot_plan, :explanations

      def initialize(app_root:, boot_plan:, explanations: {})
        @app_root = Pathname.new(app_root).expand_path
        @boot_plan = boot_plan
        @explanations = explanations || {}
      end

      def write(path)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, source)
      end

      def source
        relative = "config/application.rb"
        path = app_root.join(relative)
        lines = File.readlines(path, chomp: true)
        line_index = lines.index { |line| line.match?(/\A\s*require\s+["']rails\/all["']\s*\z/) }
        return rails_all_patch(relative, lines, line_index) if line_index

        explicit_require_patch(relative, lines)
      end

      private
        def rails_all_patch(relative, lines, line_index)
          original = lines.fetch(line_index)
          replacement = replacement_lines

          [
            "--- a/#{relative}",
            "+++ b/#{relative}",
            "@@ -#{line_index + 1},1 +#{line_index + 1},#{replacement.length} @@",
            "-#{original}",
            *replacement.map { |line| "+#{line}" },
            "",
          ].join("\n")
        end

        def explicit_require_patch(relative, lines)
          replacements = explicit_replacements(lines)
          return no_change_patch(relative) if replacements.empty?

          hunks = replacements.map do |line_index, original, replacement, comment|
            [
              "@@ -#{line_index + 1},1 +#{line_index + 1},2 @@",
              "-#{original}",
              "+#{comment}",
              "+#{replacement}",
            ]
          end

          [
            "--- a/#{relative}",
            "+++ b/#{relative}",
            *hunks.flatten,
            "",
          ].join("\n")
        end

        def explicit_replacements(lines)
          pruned_require_paths = boot_plan.pruned_frameworks.filter_map do |framework|
            BootPlan::RAILTIE_REQUIRE_PATHS[framework]
              &.then { |require_path| [framework, require_path] }
          end

          lines.each_with_index.filter_map do |line, index|
            framework, require_path = pruned_require_paths.find do |_framework, path|
              line.match?(/\A\s*require\s+#{Regexp.escape(path.dump)}\s*\z/)
            end
            next unless require_path

            [index, line, "# #{line}", pruned_comment(framework, require_path)]
          end
        end

        def replacement_lines
          [
            "# Generated by rails_dependency_pruner. Review before committing.",
            *boot_plan.require_lines,
            *pruned_replacement_lines,
          ]
        end

        def pruned_replacement_lines
          boot_plan.pruned_frameworks.flat_map do |framework|
            require_path = BootPlan::RAILTIE_REQUIRE_PATHS[framework]
            next [] unless require_path

            [
              pruned_comment(framework, require_path),
              "# require #{require_path.dump}",
            ]
          end
        end

        def pruned_comment(framework, require_path)
          details = [
            "transforms: disable_framework:#{framework}, prune_railtie:#{require_path}",
            proof_id(framework),
          ].compact.join("; ")
          "# rails_dependency_pruner: pruned #{require_path} (#{details})"
        end

        def proof_id(framework)
          return unless explanations.key?(framework)

          "proof: explanations.#{framework}"
        end

        def no_change_patch(relative)
          [
            "--- a/#{relative}",
            "+++ b/#{relative}",
            "@@ -1,0 +1,2 @@",
            "+# rails_dependency_pruner: no active prunable framework require found",
            "+# no boot-plan patch generated",
            "",
          ].join("\n")
        end
    end
  end
end
