# frozen_string_literal: true

module RailsDependencyPruner
  class BootPlan
    RAILTIE_REQUIRE_PATHS = {
      "actioncable" => "action_cable/engine",
      "actionmailbox" => "action_mailbox/engine",
      "actionmailer" => "action_mailer/railtie",
      "actionpack" => "action_controller/railtie",
      "actiontext" => "action_text/engine",
      "actionview" => "action_view/railtie",
      "activejob" => "active_job/railtie",
      "activemodel" => "active_model/railtie",
      "activerecord" => "active_record/railtie",
      "activestorage" => "active_storage/engine",
    }.freeze

    attr_reader :required_frameworks, :pruned_frameworks

    def initialize(required_frameworks:, pruned_frameworks:)
      @required_frameworks = required_frameworks.sort
      @pruned_frameworks = pruned_frameworks.sort
    end

    def require_lines
      ["require \"rails\""] + required_frameworks.filter_map do |framework|
        require_path = RAILTIE_REQUIRE_PATHS[framework]
        "require #{require_path.dump}" if require_path
      end
    end

    def pruned_lines
      pruned_frameworks.filter_map do |framework|
        require_path = RAILTIE_REQUIRE_PATHS[framework]
        "# require #{require_path.dump} # pruned by rails_dependency_pruner" if require_path
      end
    end

    def required_railties
      railties_for(required_frameworks)
    end

    def pruned_railties
      railties_for(pruned_frameworks)
    end

    def replacement_lines
      [
        "# Generated by rails_dependency_pruner. Review before committing.",
        *require_lines,
        *pruned_lines,
      ]
    end

    def to_h
      {
        "required_frameworks" => required_frameworks,
        "pruned_frameworks" => pruned_frameworks,
        "required_railties" => required_railties,
        "pruned_railties" => pruned_railties,
        "require_lines" => require_lines,
        "pruned_lines" => pruned_lines,
      }
    end

    private
      def railties_for(frameworks)
        frameworks.filter_map { |framework| RAILTIE_REQUIRE_PATHS[framework] }.sort
      end
  end
end
