# frozen_string_literal: true

require "fileutils"

module RailsDependencyPruner
  class ShimWriter
    attr_reader :constants, :require_paths

    def initialize(constants, require_paths: [])
      @constants = constants.to_a.sort
      @require_paths = require_paths.to_a.sort
    end

    def write(path)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, source)
    end

    def source
      <<~RUBY
        # frozen_string_literal: true

        require "set"

        # Generated by rails_dependency_pruner.
        # Installs fail-fast guards for Rails constants outside the observed app dependency closure.
        module RailsDependencyPrunerShim
          DisabledConstantError = Class.new(StandardError)
          DISABLED_CONSTANTS = #{constant_array_source}.freeze
          DISABLED_REQUIRE_PATHS = #{require_path_array_source}.freeze

          def self.install!(constants = DISABLED_CONSTANTS, force: false)
            install_require_guard!(DISABLED_REQUIRE_PATHS)

            constants.sort_by { |name| name.count("::") }.each do |name|
              install_constant(name, force: force)
            end
          end

          def self.install_require_guard!(paths)
            return if paths.empty? || @require_guard_installed

            disabled_paths = paths.flat_map { |path| [path, path.delete_suffix(".rb")] }.to_set
            require_guard = Module.new do
              define_method(:require) do |path|
                if disabled_paths.include?(path.to_s)
                  raise DisabledConstantError, "\#{path} is disabled by RailsDependencyPrunerShim"
                end

                super(path)
              end
            end

            Kernel.prepend(require_guard)
            @require_guard_installed = true
          end

          def self.install_constant(name, force:)
            parent, leaf = parent_and_leaf(name)
            return unless parent

            if parent.const_defined?(leaf, false)
              return unless force

              parent.__send__(:remove_const, leaf)
            end

            parent.const_set(leaf, guard_for(name))
          end

          def self.parent_and_leaf(name)
            parts = name.split("::")
            leaf = parts.pop
            parent = Object

            parts.each do |part|
              return [nil, leaf] unless parent.const_defined?(part, false)

              parent = parent.const_get(part, false)
            end

            [parent, leaf]
          end

          def self.guard_for(name)
            Class.new(BasicObject) do
              define_singleton_method(:const_missing) do |missing|
                ::Kernel.raise DisabledConstantError, "\#{name}::\#{missing} is disabled by RailsDependencyPrunerShim"
              end

              define_singleton_method(:method_missing) do |method_name, *|
                ::Kernel.raise DisabledConstantError, "\#{name}.\#{method_name} is disabled by RailsDependencyPrunerShim"
              end

              define_singleton_method(:respond_to_missing?) { |*, **| false }

              define_method(:initialize) do |*|
                ::Kernel.raise DisabledConstantError, "\#{name}.new is disabled by RailsDependencyPrunerShim"
              end
            end
          end
        end

        RailsDependencyPrunerShim.install!
      RUBY
    end

    private
      def constant_array_source
        array_source(constants)
      end

      def require_path_array_source
        array_source(require_paths)
      end

      def array_source(values)
        return "[]" if values.empty?

        "[\n" \
          "#{values.map { |value| "    #{value.dump}" }.join(",\n")}\n" \
          "  ]"
      end
  end
end
