# frozen_string_literal: true

require "fileutils"

module RailsDependencyPruner
  class ShimWriter
    attr_reader :constants

    def initialize(constants)
      @constants = constants.to_a.sort
    end

    def write(path)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, source)
    end

    def source
      <<~RUBY
        # frozen_string_literal: true

        # Generated by rails_dependency_pruner.
        # Installs fail-fast guards for Rails constants outside the observed app dependency closure.
        module RailsDependencyPrunerShim
          DisabledConstantError = Class.new(StandardError)
          DISABLED_CONSTANTS = #{constant_array_source}.freeze

          def self.install!(constants = DISABLED_CONSTANTS, force: false)
            constants.sort_by { |name| name.count("::") }.each do |name|
              install_constant(name, force: force)
            end
          end

          def self.install_constant(name, force:)
            parent, leaf = parent_and_leaf(name)
            return unless parent

            if parent.const_defined?(leaf, false)
              return unless force

              parent.__send__(:remove_const, leaf)
            end

            parent.const_set(leaf, guard_for(name))
          end

          def self.parent_and_leaf(name)
            parts = name.split("::")
            leaf = parts.pop
            parent = Object

            parts.each do |part|
              return [nil, leaf] unless parent.const_defined?(part, false)

              parent = parent.const_get(part, false)
            end

            [parent, leaf]
          end

          def self.guard_for(name)
            Class.new(BasicObject) do
              define_singleton_method(:const_missing) do |missing|
                ::Kernel.raise DisabledConstantError, "\#{name}::\#{missing} is disabled by RailsDependencyPrunerShim"
              end

              define_singleton_method(:method_missing) do |method_name, *|
                ::Kernel.raise DisabledConstantError, "\#{name}.\#{method_name} is disabled by RailsDependencyPrunerShim"
              end

              define_singleton_method(:respond_to_missing?) { |*, **| false }

              define_method(:initialize) do |*|
                ::Kernel.raise DisabledConstantError, "\#{name}.new is disabled by RailsDependencyPrunerShim"
              end
            end
          end
        end

        RailsDependencyPrunerShim.install!
      RUBY
    end

    private
      def constant_array_source
        return "[]" if constants.empty?

        "[\n" \
          "#{constants.map { |constant| "    #{constant.dump}" }.join(",\n")}\n" \
          "  ]"
      end
  end
end
